### ISSUE TITLE
How can i get Decrypted Video File

### ISSUE THREAD

**Issue by hardik24895** [rameshvoltella/VideoChunkFileEncrypter#10]

**Comment by rameshvoltella** [comment]
it is doing via exo player by giving the decryption code.same logic as [here](https://github.com/rameshvoltella/VideoChunkFileEncrypter/blob/master/app/src/main/java/com/ramzi/chunkproject/encryption/CipherDecryption.java)

**Comment by hardik24895** [comment]
> it is doing via exo player by giving the decryption code.same logic as [here](https://github.com/rameshvoltella/VideoChunkFileEncrypter/blob/master/app/src/main/java/com/ramzi/chunkproject/encryption/CipherDecryption.java)

i want decrpyted file and store it to other location is it possible

**Comment by rameshvoltella** [comment]
yes its possible,but my library concept is to make decryption while playing am not storing the decryption file anywere,So if we decrypt the file and store any one can access it,if it a rooted device its very simple

**Comment by hardik24895** [comment]
but i need to decrypt the file and store to its original location when user click on decrypt option can you please guide on this thanks in advanced.

**Comment by rameshvoltella** [comment]
```
byte[] key = CipherCommon.PBKDF2(secetKey.toCharArray(), CipherCommon.salt);
        SecretKeySpec mSecretKeySpec = new SecretKeySpec(key, CipherCommon.AES_ALGORITHM);
        IvParameterSpec mIvParameterSpec = new IvParameterSpec(CipherCommon.iv);
        Cipher mCipher = null;
        try {
            mCipher = Cipher.getInstance(CipherCommon.AES_TRANSFORMATION);
            mCipher.init(Cipher.DECRYPT_MODE, mSecretKeySpec, mIvParameterSpec);
        } catch (Exception e) {
            e.printStackTrace();
        }
```

This core of decryption use the line and write to a file location and also **secetKey** is the key you used to decrypt the data, if you still confused you use the [this code](https://github.com/rameshvoltella/VideoChunkFileEncrypter/blob/master/app/src/main/java/com/ramzi/chunkproject/encryption/CipherEncryption.java) just replace the line from 74 to 83 with the line i have given above also make sure use the file extension in the following line in my code i use .enc for you use txt,mp4 etc as per your need of file type
