### ISSUE TITLE
Some information

### ISSUE THREAD

**Issue by Angelk90** [rameshvoltella/VideoChunkFileEncrypter#8]
Hi @rameshvoltella, Congratulations on the project.

Can I ask you a few questions about how you made the player based on exoplayer?

**Comment by rameshvoltella** [comment]
Ya sure you can contact me on my personal email codemasterramz@gmail.com, abut this

**Comment by Angelk90** [comment]
@rameshvoltella :  I sent you an email some time ago, did you not receive it by chance?

**Comment by rameshvoltella** [comment]
Whats the mail subject?

**Comment by Angelk90** [comment]
@rameshvoltella : Some information VideoChuckFileEncrypter

**Comment by rameshvoltella** [comment]
Send again to codemasterramz@gmail.com
